### ISSUE TITLE
通用新增/编辑模板新增时间日期控件

### ISSUE THREAD

**Issue by mikemintang** [mikemintang/douchat#1]
使用日期时间控件增加豆信封装的通用模板，可以在控制器中通过`addFormField('name','title','date')`或者`addFormField('name','title','time')`进行调用

**Comment by sujianchao** [comment]
在使用日期时间空间时，addFormField需配合addAuto对时间进行自动转换` ->addFormField('booktime', '预约时间', 'time')`` ->addAuto('booktime',strtotime(I('post.booktime')))`
