### ISSUE TITLE
CommonController 里的 addButton 和 addListItem 方法建议给参数都添加一个默认值……

### ISSUE THREAD

**Issue by bear-shen** [mikemintang/douchat#37]
https://github.com/mikemintang/douchat/blob/4720fbb54719e5100739aaccb5dd0628e0ca46d5/App/Common/Controller/CommonController.class.php#L866

addButton 的 $url

https://github.com/mikemintang/douchat/blob/4720fbb54719e5100739aaccb5dd0628e0ca46d5/App/Common/Controller/CommonController.class.php#L758

addListItem 的 $format 和 $extra

首次安装这几块会报一堆bug……

**Comment by mikemintang** [comment]
已修复。https://github.com/mikemintang/douchat/commit/1671e8497efc21f890808cad75ddee629cfc809d
