### ISSUE TITLE
chrome下，后台上传图片点击选择图片延迟的问题

### ISSUE THREAD

**Issue by wuxianlijiang** [mikemintang/douchat#6]
ue上传图片亦存在图样问题。
如：公众号-编辑公众号-选择图片-  卡住3~·10S

解决方法：以下代码中 image/* 改为   image/gif,image/jpeg,image/png,image/jpg,image/bmp
<input type="file" capture="camera" name="file" class="webuploader-element-invisible" accept="image/*">

参考：https://www.lijiangtv.com/home.php?mod=space&uid=1&do=blog&id=11890

**Comment by mikemintang** [comment]
这个问题我发现好久了，我一直以为是我浏览器的问题，没想到改一下代码可以修复。谢谢贡献。
